language: python

cache:
        pip: true

before_install:
        - pip install codecov

install:
        - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
        - source $HOME/.poetry/env
        - pip install pip -U
        - pip install git+https://github.com/kipyin/pokedex
        - poetry install -v

script:
        - invoke test

jobs:
        include:
                - python: "3.6.5"
                - python: "3.7.1"
                  dist: xenial

after_success:
        - codecov

notification:
        email: false
