language: python

cache:
        pip: true

before-install:
        - pip install codecov

install:
        - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
        - source $HOME/.poetry/env
        - poetry install -v

script:
        - poetry run pytest -qx -cov=./pokemaster/

jobs:
        include:
                - python: "3.6"
                - python: "3.7"
                  dist: xenial
                        

