language: python
python:
        - "3.6"
        - "3.7"
install:
        - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
        - set PATH $HOME/.poetry/bin $PATH
        - poetry install -D -v
script:
        - pytest

