language: python

cache:
        pip: true

before_install:
        - pip install codecov

install:
        - make install

script:
        - make test

jobs:
        include:
                - python: "3.6"
                - python: "3.7"
                  dist: xenial

after_success:
        - codecov
