dist: xenial
language: python

cache:
  pip: true

before_install:
  - pip install codecov

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - pip install --upgrade tox

script:
  - tox

matrix:
  fast_finish: true
  include:
    # test
    - python: "3.6.5"
      stage: test
      env: TOXENV=py36
    - python: "3.7.1"
      stage: test
      env: TOXENV=py37

after_success:
  - codecov

notification:
  email: false
