language: python

cache:
        pip: true

before_install:
        - pip install codecov

install:
        - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
        - source $HOME/.poetry/env
        - poetry install -v

script:
        - make test

jobs:
        include:
                - python: "3.6"
                - python: "3.7"
                  dist: xenial

after_success:
        - codecov

notification:
        email: false
