language: python
python:
        - "3.6"
        - "3.7.1"

install:
        - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
        - source $HOME/.poetry/env
        - poetry install -v
script:
        - pytest

