[tool.poetry]
name = "pokemaster"
version = "0.1.0"
description = ""
authors = ["Kip Yin <kipyyin@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
pokedex = { git = "https://github.com/kipyin/pokedex.git", branch = "develop" }
sqlalchemy = "^1.2"

[tool.poetry.dev-dependencies]
pytest = "^4.0"
black = { version = "^18.3-alpha.0", allows-prereleases = true }
mypy = "^0.650.0"

[tool.black]
line-length = 80
py36 = true
skip-string-normalization = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
